[platformio]
workspace_dir = ${sysenv.USERPROFILE}/.pfxpio/tx
default_envs = t190_sender

[env:t190_sender]
platform = espressif32@7.0.1
board = esp32-s3-devkitc-1
framework = arduino
extra_scripts = pre:scripts/ensure_esptool_python_deps.py
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
upload_speed = 460800

; Heltec Vision Master T190: ESP32-S3R8, 16 MB flash, 8 MB OPI PSRAM
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.partitions = huge_app.csv

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1
    -DPFX_ROLE_SENDER=1

lib_deps =
    https://github.com/jgromes/RadioLib/archive/refs/tags/7.7.1.zip
    adafruit/Adafruit GFX Library@1.12.1
    adafruit/Adafruit ST7735 and ST7789 Library@1.11.0
